version: "3.8"

services:
  service:
    build: .
    links:
      - redis:redis
      - mysql:mysql
    depends_on:
      - redis
      - mysql
  honeytail:
    image: honeytail:latest
    volumes:
      - nginxtmp:/tmp
    depends_on:
      - nginx
  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - nginxtmp:/tmp
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/nginx.conf:/tmp/nginx.conf
    ports:
      - 80:80
    links:
      - service:service
  redis:
    image: redis:7.0.2
  mysql:
    image: mysql:5.7.38
    volumes:
      - honeycomb:/var/lib/mysql
      - ./config/sql:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_PASSWORD: honeycomb
      MYSQL_ROOT_PASSWORD: honeycomb
      MYSQL_DATABASE: honeycomb

volumes:
  honeycomb:
  nginxtmp: